services:
  backend-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
